version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kafka_game_coordinator
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - './mysql-startup:/docker-entrypoint-initdb.d'
    ports:
      - "3306:3306"
